### ISSUE TITLE
Pretrained files mix up

### ISSUE THREAD

**Issue by priyatarigopula02** [BKHMSI/alchemist#1]
Hello, 

Thank you very much for the nice work.
I have run the 1000 test episodes with both pretrained models and find that the results are reversed. 
I suppose there has been a mix up in the names of the files in the corresponding links.

Kindly check !

![a2c_epn_wo_penalties](https://user-images.githubusercontent.com/93142418/154092633-13687bcd-394a-4bb6-80e1-51b249024ef1.png)

![a2c_epn](https://user-images.githubusercontent.com/93142418/154092598-a15460e0-1234-4a58-bd3e-2463ac0b373a.png)

**Comment by BKHMSI** [comment]
Hi,

Thank you for your interest in this project and pointing out this mistake, I switched the name of the files accordingly!
